### ISSUE TITLE
Text in Message after attempt to connect to WiFi

### ISSUE THREAD

**Issue by anwarbashir** [zhouhan0126/WIFIMANAGER-ESP32#8]
Hi,

I am trying to change the message that appears after wifimanager tries to connect. Currently there is a typo and I want to fix or even change the message. I have tried to search for the words but no luck. Can you advise which file to amend? Currently the message is:

Weread to network if it fails reconnect to AP to try again.

**Comment by DevSpur** [comment]
@anwarbashir Hi I found the place where you can change the message you can locate to the wifimanager.h file and edit it there

**Comment by anwarbashir** [comment]
Hi, Thank you, I will take a look - much obliged.

**Comment by anwarbashir** [comment]
Yes, Yehh it's in line 52. Not sure why I did not see it before. Thanks again
